/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
    "aws_project_region": "us-east-2",
    //"aws_cognito_identity_pool_id":"us-east-2:f0bea4ec-2fa2-4200-8163-3106bf2ea79f",
    "aws_cognito_region": "eus-east-2",
    "aws_user_pools_id": "us-east-2_ihndhBv4b",
    "aws_user_pools_web_client_id": "7ng3pt7n231dkgg4tqh1bj8hrd",
    "oauth": {
        "domain": "wrf-nwcd.auth.us-east-2.amazoncognito.com"
    },
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "WrfAPIGateway",
            "endpoint": "https://olvazo4hp8.execute-api.us-east-2.amazonaws.com/prod",
            "region": "us-east-2"
        }
    ],
    "geo": {
        "amazon_location_service": {
          "region": "us-east-2",
          "maps": {
            "items": {
              "react-map-with-geojson-example": {
                "style": "VectorEsriStreets"
              }
            },
            "default": "react-map-with-geojson-example",
            "apikey":"v1.public.eyJqdGkiOiIxZTYzMDljNy05M2VlLTQ4N2YtYTM1Ni00NTU5MGEyZDc0ZjAifTBkyDYHdR8QLJrtwEWTisUJhCXgglExOpd9iK0Ur4TVUH8EsPZWpbKOv1wLUsv_r12t_OUvAwkUhIAEJXeRLulLdKELbl3u1oCbB_JhemL0N_c11KDYl2X5x0uHT86BD-wB1qpHT7_Oi9cVz_Y2sRZwi9tBA1QxLLKu18Xjfy5XlZGn5g-RgKuMZTu1wA-JsO8HHjwYWyL3WExbQy_omG0S5vCnVvMHc33hShKPHJVqzbrfxLZHUY7KoNM3x_bicztO8--rkrdaFWrzpHIFcSiJ6tJYggjWHz60WKXwf0E1UxnQPTpH_XS5xl1jGR-VbDOnw1cvLGgKNJFM_tc7HYs.NjAyMWJkZWUtMGMyOS00NmRkLThjZTMtODEyOTkzZTUyMTBi"
  
          }
        }
    }

};


export default config;